//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenusAPIlib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuEntry
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Moment { get; set; }
        public int NumCalories { get; set; }
    
        public virtual User User { get; set; }
    }
}
